languageCode: "en-us"
baseUrl: ""
title: "snowmerak"
theme: "mini"
paginate: 10
googleAnalytics: "G-1MV53Q3MRL"
enableRobotsTXT: true
disqusShortname: "snowmerak"

menu:
  main:
  - identifier: archive
    name: Posts
    title: Posts
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0

social:
  github: github.com/snowmerak

params:
  enableComments: true