languageCode: "en-us"
baseUrl: ""
title: "snowmerak"
theme: "LoveIt"
googleAnalytics: "G-1MV53Q3MRL"

menu:
  main:
  - identifier: archive
    name: Posts
    title: Posts
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0

params:
  # Site Author
  author: snowmerak
  # Author biography
  bio: programmer

  enableGoogleAnalytics: true
  showToc: true
  showPowerBy: true